### ISSUE TITLE
Cannot resolve the collation conflict

### ISSUE THREAD

**Issue by sbaxterg** [gtaylor44/SqlBulkTools#19] opened 2016-11-14 10:20 UTC
Hi,

I'm having troubles to make an BulkInsertOrUpdate, I receive the error "Cannot resolve the collation conflict between "Latin1_General_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in the equal to operation."

The server that runs the SQL Server has a default collation of "Latin1_General_CI_AS" but the database that I'm trying to update has a collation of "SQL_Latin1_General_CP1_CI_AS". It looks like the tool needs to set up the database collation in the generated sql to do the job right.

Is possible to solve that?

Thanks.

Scott.

**Comment by gtaylor44** [comment] 2016-11-14 11:49
May I ask if there is a specific reason or desired goal for mixing collations? For this I'm thinking another configuration option added when selecting table which will set collation explicitly in queries to resolve the conflict.

**Comment by gtaylor44** [comment] 2016-11-14 12:32
I will post a fix for this issue tomorrow.

**Comment by sbaxterg** [comment] 2016-11-15 08:50
I don't really know why the sql server has a different collation than the database (maybe a migration), but unfortunately I don't have the control to change it and currently is working without any problem.

BTW, your library rocks!!!

**Comment by gtaylor44** [comment] 2016-11-16 09:27
Thanks for the compliments. I've just published v3.06 to resolve collation conflicts. Let me know how you go. 

```
..
BulkInsertOrUpdate()
.SetCollationOnColumn(column, collation)
..
```

**Comment by sbaxterg** [comment] 2016-11-16 12:09
My problem is not one column, all the columns in the table (and the whole database) have different collation than the sql server, so instead to one column could be applied to all columns so I don't have to specify each one? (my table has 144 columns)

**Comment by gtaylor44** [comment] 2016-11-16 13:45
Wow thats one wide table. The challenge with setting it globally is type matching. Integers for example would throw an exception if you set a collation. Try setting a collation on the join (MatchTargetOn) columns.

**Comment by sbaxterg** [comment] 2016-11-16 16:37
Just setting the collation on the columns in MatchTargetOn looks like is enough. MANY THANKS!

**Closed** 2016-11-27 13:24 UTC

**Comment by OptimusPrimeGitHub** [comment] 2017-01-20 16:29
Hi GTAYLOR44  ! 
Thanks a lot for your library ! Very good job. it save me a lot of time of work.
I have the same issue : "Cannot resolve the collation conflict between "French_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in the equal to operation." Please, can you explain me in the detail how you and "sbaxterg " proceed to set the collation on all columns in one time ? Because i'm not able to set in MatchTargetOn, because i thibk it's only accept lambda expression.
Example : 
bulk.Setup<SIRENE>()
                            .ForCollection(listOfSirene)
                            .WithTable("SIRENE")
                            .AddAllColumns()
                            .BulkInsertOrUpdate()
                            .MatchTargetOn(s => s.SIREN)
                            .MatchTargetOn(s => s.NIC)
                            .Commit(dbConnection);

I have more than hundred columns that's why i don't want to iterate the following line 

.SetCollationOnColumn(c => c.COL1, "SQL_Latin1_General_CP1_CI_AS")
.SetCollationOnColumn(c => c.COL2, "SQL_Latin1_General_CP1_CI_AS")
.SetCollationOnColumn(c => c.COL3, "SQL_Latin1_General_CP1_CI_AS")
etc ....

Thanks in advance for your return.

**Comment by gtaylor44** [comment] 2017-01-21 06:34
You only need to use SetCollationOnColumn for the columns that you're matching your target on. This this case SIREN and NIC. It's on my to do list to make collation an overload for MatchTargetOn instead of having it as a separate expression. 

Try this...
```
.SetCollationOnColumn(c => c.SIREN, "SQL_Latin1_General_CP1_CI_AS")
.SetCollationOnColumn(c => c.NIC, "SQL_Latin1_General_CP1_CI_AS")
```

**Comment by gtaylor44** [comment] 2017-01-21 06:51
And just an FYI to everybody...

It's best to keep your collation consistent if you can. By explicitly casting collation, you lose the benefits of indexing and a full table scan is unavoidable. There could also be unexpected behaviour in some cases depending on the collation source. Just want to put that warning out there.

**Comment by OptimusPrimeGitHub** [comment] 2017-01-23 09:21
Perfect !!!

The solution you gave me works as expected.
Thanks for your advices about keeping collation consistent.

Sincerely !
